### ISSUE TITLE
#Commits may be incorrect

### ISSUE THREAD

**Issue by kiszk** [maropu/spark-tpcds-datagen#1]
While hash values in two rows are different, #commits is 0. For example, rows 12 and 13.

**Comment by maropu** [comment]
yea, thanks! I've noticed that and I probably recently fixed the issue. I'll close this after we can see correct #commits.

**Comment by maropu** [comment]
It seems it works well: https://github.com/maropu/spark-tpcds-datagen/commit/f0726f21ce4db6378adcc35171e7bf307c49f270
