### ISSUE TITLE
Add a new column to see all of commits between two rows

### ISSUE THREAD

**Issue by kiszk** [maropu/spark-tpcds-datagen#3]
Is it possible to add a new column to see all of commits between two rows?

It may be possible to use create an URL by including two times.
http://qiita.com/sotayamashita/items/1cf05f2a2be3d6fb3388#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AE%E6%AF%94%E8%BC%83

**Comment by maropu** [comment]
See: https://docs.google.com/spreadsheets/d/1V8xoKR9ElU-rOXMH84gb5BbLEw0XAPTJY8c8aZeIqus/edit#gid=445143188
