### ISSUE TITLE
Schema mismatch from Spark while using TPCDSQueryTestSuite

### ISSUE THREAD

**Issue by sunchao** [maropu/spark-tpcds-datagen#8]
I'm trying to run `TPCDSQueryTestSuite` using data generated via this repo, but got the following error:
```
09:49:50.720 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 0.0 in stage 11.0 (TID 13925) (192.168.86.187 executor driver): org.apache.spark.sql.execution.QueryExecutionException: Parquet column cannot be converted in file file:/Users/sunchao/tpcds-sf-1/store_returns/sr_returned_date_sk=2451908/part-00000-02af72a9-8d23-4ec5-94b3-30828fa5ace4.c000.snappy.parquet. Column: [sr_customer_sk], Expected: int, Found: INT64
```
I think this is due to a mismatch between Spark read schema and Parquet schema. From Spark side, this column is `INT` (see [here](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/TPCDSSchema.scala#L75)) while Parquet schema is `INT64` (see [here](https://github.com/maropu/spark-tpcds-datagen/blob/master/src/main/scala/org/apache/spark/sql/execution/benchmark/TPCDSDatagen.scala#L355)).

**Comment by sunchao** [comment]
cc @maropu - do you think this worth a fix?

**Comment by maropu** [comment]
Ah, yea. Thanks for letting me know.  It seems I forgot to sync the schema. Yes, that should be fixed.

**Comment by maropu** [comment]
Fixed in https://github.com/maropu/spark-tpcds-datagen/commit/13e67a3e92dca21c7546e3f118c90a2dc0f5c44d
