### ISSUE TITLE
Where can i find class or object TPCDSQueryBenchmark ?

### ISSUE THREAD

**Issue by luckyplusten** [maropu/spark-tpcds-datagen#9]
Hi 
Such a great work !!!  Just a little question, where can i find class or object TPCDSQueryBenchmark ?  I can'd find it in the src codes
Best Regards
MA Yue

**Comment by luckyplusten** [comment]
@maropu

**Comment by maropu** [comment]
Hi, @luckyplusten, that exists in the Spark repository, please see: https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/execution/benchmark/TPCDSQueryBenchmark.scala

**Comment by maropu** [comment]
FYI: the current master in the spark repo. can generate TPCDS test dataset via `GenTPCDSData`. Please see:
https://github.com/apache/spark/blob/21450b325457573265b2bf66e3ef7dd27453978e/sql/core/src/test/scala/org/apache/spark/sql/GenTPCDSData.scala#L407-L415
```
build/sbt "sql/test:runMain <this class> --dsdgenDir <path> --location <path> --scaleFactor 1"
```
